/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_NdkNativeJava */

#ifndef _Included_com_example_ndk_NdkNativeJava
#define _Included_com_example_ndk_NdkNativeJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_NdkNativeJava
 * Method:    getCallResultByC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_NdkNativeJava_getCallResultByC
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndk_NdkNativeJava
 * Method:    updateFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NdkNativeJava_updateFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_ndk_NdkNativeJava
 * Method:    writeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NdkNativeJava_writeFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_ndk_NdkNativeJava
 * Method:    updateIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ndk_NdkNativeJava_updateIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_example_ndk_NdkNativeJava
 * Method:    updateIntArrayByPointer
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ndk_NdkNativeJava_updateIntArrayByPointer
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_example_ndk_NdkNativeJava
 * Method:    testJavahEclipseConfigTool
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NdkNativeJava_testJavahEclipseConfigTool
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
